
title: Консультант по маркетингу и стратегии | Дмитрий Бартошевич
description: >- # this means to ignore newlines until "baseurl:"
  Развиваю бренды, опираясь на&nbsp;исследования и&nbsp;анализ данных. Разрабатываю план необходимых действий, контролирую реализацию. Противник &laquo;втюхинга&raquo; и&nbsp;манипуляций.
baseurl: "" 
url: "https://doc2022.netlify.app" 


sass:
  style: compressed
  sass_dir: _sass
   

include: _redirects     

# Build settings

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
