title: "Консультант по маркетингу и стратегии | Дмитрий Бартошевич"
description: "Развиваю бренды, опираясь на исследования и анализ данных. Разрабатываю план необходимых действий, контролирую реализацию. Противник 'втюхинга' и манипуляций."
baseurl: "" 
url: "https://bartoshevich.by" 

sass:
  style: compressed
  sass_dir: _sass

compress_html:
  comments: ["<!-- ", " -->"]
  endings: all

include: 
  - _redirects
  - _headers     

# Build settings
plugins:
  - jekyll-feed
  - jekyll-minifier

jekyll-minifier:
  javascript: true
  javascript_compression: uglifier
  javascript_options:
    harmony: true
    compress: true
    mangle: true



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
